#
# This Dockerfile is used for locally running Playwright in a Linux environment.
# We do this to ensure our reference images for visual regression tests are the same during development and in CI.
#

FROM mcr.microsoft.com/playwright:v1.43.1-jammy

WORKDIR /work

RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile