#
# This Dockerfile is used for locally running Playwright in a Linux environment.
# We do this to ensure our reference images for visual regression tests are the same during development and in CI.
#

FROM mcr.microsoft.com/playwright:v1.45.0-jammy@sha256:87742f12debf99873b69d166f6a02b8e7a6f47ddb51d9dfdb708849898fe11d1

WORKDIR /work

RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile