name: 'YC Serverless Container Public'
description: 'GitHub Action to make Serverless Container public'
author: 'Iakhub Seitasanov'
inputs:
  yc-sa-json-credentials:
    required: true
    description: 'Json containing authorized key for Service Account. More info https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json'
  container-id:
    required: true
    description: 'Id of serverless container'
branding:
  color: blue
  icon: upload-cloud
runs:
  using: 'node20'
  main: 'dist/index.js'
