global:
  scrape_interval: 10s # Default is every 1 minute.

scrape_configs:
  # - job_name: 'otel-collector'
  #   static_configs:
  #     - targets: ['otel-collector:8889']
  #     - targets: ['otel-collector:8888']
  - job_name: 'opentelemetry'
    static_configs:
      - targets: ['host.docker.internal:9464']
