#cloud-config
write_files:
  - content: |
      [SERVICE]
          Flush         1
          Log_File      /var/log/fluentbit.log
          Log_Level     error
          Daemon        off
          Parsers_File  /fluent-bit/etc/parsers.conf

      [FILTER]
          Name parser
          Match app.logs
          Key_Name log
          Parser app_log_parser
          Reserve_Data On

      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              24224
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   6M

      [OUTPUT]
          Name            yc-logging
          Match           *
          group_id        $${YC_GROUP_ID}
          message_key     log
          level_key       severity
          default_level   INFO
          default_payload {"host":"{{instance/hostname}}"}
          resource_type   vm
          resource_id     {{instance/id}}
          stream_name     {container_name}
          authorization   instance-service-account
    path: /etc/fluentbit/fluentbit.conf
  - content: |
      [PARSER]
          Name   app_log_parser
          Format regex
          Regex  .*
    path: /etc/fluentbit/parsers.conf
  - content: |
      scrape_configs:
        - job_name: 'opentelemetry'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:9464']
      remote_write:
        - url: 'https://monitoring.api.cloud.yandex.net/prometheus/workspaces/monahld83gdk2at8l9r9/api/v1/write'
          bearer_token: ${prometheus_rw_api_key}
          queue_config:
            max_samples_per_send: 2000
            min_backoff: 100ms
            max_backoff: 15s
            retry_on_http_429: true
          metadata_config:
            send: false
    path: /etc/prometheus/prometheus.yml

groups:
  - docker
ssh_pwauth: no
users:
  - name: ${user}
    groups: sudo, docker, systemd-journal
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - '${ssh_key}'
