#cloud-config
write_files:
  - content: |
      [SERVICE]
          Flush         1
          Log_File      /var/log/fluentbit.log
          Log_Level     error
          Daemon        off
          Parsers_File  /fluent-bit/etc/parsers.conf

      [FILTER]
          Name parser
          Match app.logs
          Key_Name log
          Parser app_log_parser
          Reserve_Data On

      [FILTER]
          Name parser
          Match ua.logs
          Key_Name log
          Parser ua_log_parser
          Reserve_Data On

      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              24224
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   6M

      [OUTPUT]
          Name            yc-logging
          Match           *
          group_id        $${YC_GROUP_ID}
          message_key     log
          level_key       level
          default_level   INFO
          default_payload {"host":"{{instance/hostname}}"}
          resource_type   vm
          resource_id     {{instance/id}}
          stream_name     {container_name}
          authorization   instance-service-account
    path: /etc/fluentbit/fluentbit.conf
  - content: |
      [PARSER]
          Name   app_log_parser
          Format regex
          Regex  .*
      [PARSER]
          Name   ua_log_parser
          Format regex
          Regex  ^(?<time>[^ ]+) (?<severity>\d+) (?<unique_id>\d+) (?<level>[A-Z]+) (?<message>.*?)(?:, revision \[(?<revision>\d+)\])?(?: \[:(?<service_id>\d+)\])?$
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%NZ
          Time_Keep   On
    path: /etc/fluentbit/parsers.conf
  - content: |
      agent_log:
        priority: INFO
      routes:
        - input:
            plugin: metrics_pull
            config:
              url: http://app:9464/metrics
              format:
                prometheus: {}
              namespace: app
          channel:
            channel_ref:
              name: cloud_monitoring
    path: /etc/unified_agent/config.yml
  - content: |
      [Journal]
      ForwardToConsole=yes
      TTYPath=/dev/ttyS0
      MaxLevelConsole=info
    append: true
    path: /etc/systemd/journald.conf

groups:
  - docker
ssh_pwauth: no
users:
  - name: ${user}
    groups: sudo, docker, systemd-journal
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - '${ssh_key}'
