name: Build and push docker image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: Environment name
        type: string
      cdn:
        required: true
        description: CDN origin
        type: string
    secrets:
      YC_SA_JSON_CREDENTIALS:
        description: Json, содержащий авторизованные ключи для сервисного аккаунта. Подробнее https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json
      DOCKER_REGISTRY_PATH:
      AWS_S3_BUCKET:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      SENTRY_AUTH_TOKEN:
      SENTRY_ORG:
      SENTRY_PROJECT:
    outputs:
      docker_image:
        description: Полное имя (тег) собранного docker-образа
        value: ${{ jobs.build-push.outputs.docker-image-version }}

jobs:
  # Сборка и публикация docker-образа
  build-push:
    name: Image
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      docker-image-version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Create Sentry release
        id: sentry-release
        uses: getsentry/action-release@e769183448303de84c5a06aaaddf9da7be26d6c7 # 1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ inputs.environment }}
          version: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ secrets.DOCKER_REGISTRY_PATH }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@b3f9f3de6a883203431aeec20f3cc602fafd3a05 # v2.0.0
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      # https://docs.docker.com/build/ci/github-actions/cache/
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        env:
          awsEndpoint: https://storage.yandexcloud.net
          staticPath: ${{ github.event_name == 'pull_request' && format('pr/{0}', github.event.pull_request.number) || format('releases/{0}', steps.sentry-release.outputs.version) }}
        with:
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY_PATH }}:latest
          # cache-to: type=inline
          build-args: |
            ENV=${{ inputs.environment }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
            AWS_ENDPOINT_URL=${{ env.awsEndpoint }}
            AWS_DEFAULT_REGION=ru-central1
            AWS_S3_PATH=${{ env.staticPath }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
            SENTRY_RELEASE=${{ steps.sentry-release.outputs.version }}
            ASSET_PREFIX=https://${{ inputs.cdn }}/${{ env.staticPath }}
