name: Chromatic

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  SKIP_SIMPLE_GIT_HOOKS: 1

jobs:
  chromatic:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    environment:
      name: Storybook
      url: ${{ steps.chromatic-deploy.outputs.storybookUrl }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        id: chromatic-deploy
        uses: chromaui/action@a7f65ed179bcbe19fd793367d699f43e0f0540a7 # v11.3.5
        with:
          exitZeroOnChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'master'
          skip: 'dependabot/**'
