name: Chromatic

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  SKIP_SIMPLE_GIT_HOOKS: 1

jobs:
  chromatic:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    environment:
      name: Storybook
      url: ${{ steps.chromatic-deploy.outputs.storybookUrl }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        id: chromatic-deploy
        uses: chromaui/action@5991575112b472a4fa85429f29cc17e2fb83a2a2 # v11.5.4
        with:
          exitZeroOnChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'master'
          skip: 'dependabot/**'
