name: Deploy

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

env:
  S3_PATH: ${{ github.event_name == 'pull_request' && format('pr/{0}', github.event.pull_request.number) || 'production' }}

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      docker-image-version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      # TODO: https://docs.docker.com/build/ci/github-actions/cache/
      # - name: Cache pnpm-store
      #   uses: actions/cache@v3
      #   with:
      #     path: pnpm-store
      #     key: pnpm-store-${{ hashFiles('Dockerfile') }}

      # - name: Inject pnpm-store into docker
      #   uses: reproducible-containers/buildkit-cache-dance@v2.1.3
      #   with:
      #     cache-source: pnpm-store
      #     cache-target: /pnpm/store

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          build-args: |
            ASSET_PREFIX=https://${{ github.event_name == 'pull_request' && format('storage.yandexcloud.net/{0}', secrets.AWS_S3_BUCKET) || 'cdn.r34s0n.tech' }}/${{ env.S3_PATH }}

  upload-static:
    name: Upload static to S3
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Copy static files from docker image
        run: |
          docker pull cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}:${{ needs.build-push.outputs.docker-image-version }}
          docker run -i --name helper cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}:${{ needs.build-push.outputs.docker-image-version }} true
          docker cp helper:/app/.next .
          docker rm helper

      - name: Sync static assets to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: aws s3 --endpoint-url=https://storage.yandexcloud.net sync .next/static s3://${{ secrets.AWS_S3_BUCKET }}/${{ env.S3_PATH }}/_next/static

  deploy:
    name: Deploy
    needs: [build-push]
    environment:
      name: ${{ github.event_name == 'pull_request' && 'Preview' || 'Production' }}
      url: ${{ github.event_name == 'pull_request' && format('https://{0}.containers.yandexcloud.net', steps.deploy-sls-container.outputs.id) || 'https://r34s0n.tech' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: ${{ secrets.CR_REPOSITORY }}-${{ needs.build-push.outputs.docker-image-version }}
          folder-id: b1guhjmc4e8mlon8i2vl
          revision-service-account-id: ajecbk36deocemds4lar
          revision-image-url: cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}:${{ needs.build-push.outputs.docker-image-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Public Serverless Container
        uses: ./.github/actions/yc-sls-container-public
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-id: ${{ steps.deploy-sls-container.outputs.id }}

      - name: Purge CDN cache
        uses: yc-actions/yc-cdn-cache@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          cdn-resource-id: bc8eyazsip6i4r4bqjsa
