name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: Environment name
        type: string
      image_id:
        type: string
        required: true
        description: Имя собранного docker-образа
      stage_name:
        type: string
        required: true
        description: Название стенда
    secrets:
      YC_SA_JSON_CREDENTIALS:
        description: Json, содержащий авторизованные ключи для сервисного аккаунта. Подробнее https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json
      DOCKER_REGISTRY_PATH:
      DEPLOY_SA_ID:
      FOLDER_ID:
    outputs:
      domain:
        description: Доменное имя развернутого стенда
        value: ${{ jobs.deploy.outputs.domain }}

jobs:
  deploy:
    name: Terraform
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.terraform-output.outputs.domain }}/
    outputs:
      domain: ${{ steps.terraform-output.outputs.domain }}
    runs-on: ubuntu-latest
    env:
      YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      TF_CLI_CONFIG_FILE: '${{ github.workspace }}/.github/files/terraformrc'
      TF_VAR_name_prefix: ${{ inputs.stage_name }}
      TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
      TF_VAR_image_url: ${{ secrets.DOCKER_REGISTRY_PATH }}:${{ inputs.image_id }}
      TF_VAR_service_account_id: ${{ secrets.DEPLOY_SA_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_STATE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_STATE_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.1'
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: deploy/app
        run: terraform init -backend-config="key=${{ inputs.stage_name }}/terraform.tfstate"

      - name: Terraform Plan
        id: plan
        working-directory: deploy/app
        run: terraform plan -input=false -no-color -out tf.plan

      - name: Terraform Apply
        working-directory: deploy/app
        run: terraform apply -input=false tf.plan

      - name: Terraform get output
        working-directory: deploy/app
        id: terraform-output
        run: echo "domain=$(terraform output -raw api_gateway_domain)" >> "$GITHUB_OUTPUT"

      # - name: Purge CDN cache
      #   uses: yc-actions/yc-cdn-cache@v1
      #   with:
      #     yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      #     cdn-resource-id: bc8eyazsip6i4r4bqjsa

  e2e-test:
    # Хороший end-to-end тест представляет из себя более сложную конструкцию, чем curl, проверяющий статус ответа главной страницы стенда. Такой простой тест использован для целей демонстрации
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: |
          curl '${{ needs.deploy.outputs.domain }}/'
