name: Deploy

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          cache-from: type=registry,ref=cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}:${{ github.sha }}
          cache-to: type=inline
          tags: cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}:${{ github.sha }}
          build-args: |
            ASSET_PREFIX=https://storage.yandexcloud.net/${{ secrets.AWS_S3_BUCKET }}

  upload-static:
    name: Upload static to S3
    needs: publish-image
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Copy static files from docker image
        run: |
          docker pull cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}:${{ github.sha }}
          docker run -i --name helper cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}:${{ github.sha }} true
          docker cp helper:/app/.next .
          docker rm helper

      - name: Sync static assets to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: aws s3 --endpoint-url=https://storage.yandexcloud.net sync .next/static s3://${{ secrets.AWS_S3_BUCKET }}/_next/static

  deploy:
    name: Deploy
    needs: [publish-image, upload-static]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: ${{ secrets.CR_REPOSITORY }}
          folder-id: b1guhjmc4e8mlon8i2vl
          revision-service-account-id: ajecbk36deocemds4lar
          revision-image-url: cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}:${{ github.sha }}
