name: Lighthouse CI

on:
  deployment_status:

env:
  SKIP_SIMPLE_GIT_HOOKS: 1
  LHCI_COLLECT__URL: ${{ github.event.deployment_status.environment_url }}en
  LHCI_UPLOAD__TARGET: temporary-public-storage

jobs:
  lhci-mobile:
    if: |
      github.actor != 'dependabot[bot]' && github.event.deployment_status.state == 'success'
      && github.event.deployment_status.environment_url
      && (github.event.deployment_status.environment == 'development' || github.event.deployment_status.environment == 'production')
    name: Lighthouse mobile audit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Chrome
        id: install-chrome
        uses: browser-actions/setup-chrome@9683066f53b47e92c4104e1bd5535aff208c3530 # v1.6.2

      - run: pnpm lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          CHROME_PATH: ${{ steps.install-chrome.outputs.chrome-path }}

  lhci-desktop:
    if: |
      github.actor != 'dependabot[bot]' && github.event.deployment_status.state == 'success'
      && github.event.deployment_status.environment_url
      && (github.event.deployment_status.environment == 'development' || github.event.deployment_status.environment == 'production')
    name: Lighthouse desktop audit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Chrome
        id: install-chrome
        uses: browser-actions/setup-chrome@9683066f53b47e92c4104e1bd5535aff208c3530 # v1.6.2

      - run: pnpm lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          CHROME_PATH: ${{ steps.install-chrome.outputs.chrome-path }}
