name: Lighthouse CI

on:
  deployment_status:

env:
  SKIP_SIMPLE_GIT_HOOKS: 1
  LHCI_COLLECT__URL: ${{ github.event.deployment_status.environment_url }}en
  LHCI_UPLOAD__TARGET: temporary-public-storage

jobs:
  lhci-mobile:
    if: |
      github.actor != 'dependabot[bot]' && github.event.deployment_status.state == 'success'
      && github.event.deployment_status.environment_url
      && (github.event.deployment_status.environment == 'development' || github.event.deployment_status.environment == 'production')
    name: Lighthouse mobile audit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Chrome
        id: install-chrome
        uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148 # v1.7.2

      - run: pnpm lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          CHROME_PATH: ${{ steps.install-chrome.outputs.chrome-path }}

  lhci-desktop:
    if: |
      github.actor != 'dependabot[bot]' && github.event.deployment_status.state == 'success'
      && github.event.deployment_status.environment_url
      && (github.event.deployment_status.environment == 'development' || github.event.deployment_status.environment == 'production')
    name: Lighthouse desktop audit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Chrome
        id: install-chrome
        uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148 # v1.7.2

      - run: pnpm lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          CHROME_PATH: ${{ steps.install-chrome.outputs.chrome-path }}
