on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Create release PR

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple

      # Format changelog, workaround for https://github.com/google-github-actions/release-please-action/issues/542
      # Taken from https://github.com/remarkablemark/release-please-extra-files-demo/blob/master/.github/workflows/release-please.yml
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        if: ${{ steps.release.outputs.pr }}
        with:
          ref: ${{ fromJson(steps.release.outputs.pr).headBranchName }}

      - name: Configure Git user
        if: ${{ steps.release.outputs.pr }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git --no-pager show --name-only

      - name: Install pnpm
        if: ${{ steps.release.outputs.pr }}
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        if: ${{ steps.release.outputs.pr }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        if: ${{ steps.release.outputs.pr }}
        run: pnpm install

      - name: Format CHANGELOG.md
        if: ${{ steps.release.outputs.pr }}
        run: pnpm exec prettier --write CHANGELOG.md

      - name: Commit and push
        if: ${{ steps.release.outputs.pr }}
        run: |
          git add CHANGELOG.md
          git commit -m 'chore: Format CHANGELOG.md with Prettier' --no-verify
          git push
