name: Release application
on:
  push:
    branches:
      - 'master'
  # Разрешает ручной вызов действия. Может быть использовано для отката testing и prod окружений на ранее собранную версию.
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  #   release-name:
  #     runs-on: ubuntu-latest
  #     outputs:
  #       name: ${{ join(steps.*.outputs.new_tag, '') }}
  #     steps:
  #       - uses: actions/checkout@v4
  #       # В случае ручного запуска workflow из ранее созданного релизного тега,
  #       # мы не хотим создавать новый тег - нам требуется использовать выбранный пользователем.
  #       - name: Pick existing tag
  #         id: existing-tag
  #         if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
  #         run: echo '::set-output name=new_tag::${{ github.ref_name }}'
  #       - name: Bump version and push tag
  #         id: tag-release
  #         uses: mathieudutour/github-tag-action@v6.0
  #         if: steps.existing-tag.conclusion == 'skipped'
  #         with:
  #           github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    # needs: release-name
    uses: ./.github/workflows/build.yml
    with:
      environment: dev
    secrets:
      YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      DOCKER_REGISTRY_PATH: ${{ secrets.DOCKER_REGISTRY_PATH }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-prod:
    name: Deploy
    needs:
      - build
    uses: ./.github/workflows/deploy.yml
    with:
      image_id: ${{ needs.build.outputs.docker_image }}
      stage_name: production
      environment: prod
    secrets:
      YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      DOCKER_REGISTRY_PATH: ${{ secrets.DOCKER_REGISTRY_PATH }}
      DEPLOY_SA_ID: ${{ secrets.DEPLOY_SA_ID }}
      FOLDER_ID: ${{ secrets.FOLDER_ID }}
